INSERT INTO NAME () VALUES ();
INSERT INTO CLASS () VALUES ();

INSERT INTO SCHOOL () VALUES ();
INSERT INTO DISTRICT () VALUES ();

INSERT INTO CITY () VALUES ();

INSERT INTO STATE () VALUES ();
INSERT INTO COUNTRY () VALUES ();
INSERT INTO PIN () VALUES ();
INSERT INTO AREA () VALUES ();
